### ISSUE TITLE
address problem with failing tests temporarily placed in todo folder

### ISSUE THREAD

**Issue by slayoo** [vinecopulib/pyvinecopulib#15]
- [ ] bicop_ctor_1arg_data.py
- [ ] bicop_ctor_2arg_controls.py
- [ ] bicop_fit_2arg.py
- [ ] bicop_fit.py
- [ ] bicop_parameters_to_tau.py
- [ ] vinecop_all_families.py
- [ ] vinecop_all_parameters.py
- [ ] vinecop_all_rotations.py
- [ ] vinecop_ctor_1arg_data.py
- [ ] vinecop_ctor_2arg_data_controls.py
- [ ] vinecop_ctor_2arg_list_matrix.py
- [ ] vinecop_ctor_3arg_data_matrix_controls.py
- [ ] vinecop_example_2.py
- [ ] vinecop_example_3.py
- [ ] vinecop_fit_controls_ctor_4arg_controls.py
- [ ] vinecop_fit_controls_ctor_5arg_controls.py
- [ ] vinecop_fit_controls_setters.py
- [ ] vinecop_getters.py
- [ ] vinecop_setters_fail.py
