### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by tvatter** [vinecopulib/pyvinecopulib#150]
- [x]  Bicop summary (see the [vinecopulib PR](https://github.com/vinecopulib/vinecopulib/pull/588))
- [x] Investigate #129
- [x] Investigate Bicop.plot(margin_type="norm") (see #151)
- [x] Add proper labels to Vinecop.plot (see #152)
