### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by tvatter** [vinecopulib/pyvinecopulib#155]
- [x] Make version number available and include in the documentation
- [ ] Automatize docbuild with readthedocs
- [x] Investigate compiler options and speed issues
- [x] Rethink the overloaded constructors
- [ ] Make versions dynamic
- [ ] Pixi instead of conda
- [ ] Vines with automated marginals

**Comment by tvatter** [comment]
@tnagler regarding the overloaded constructors, we have essentially 3 choices:

- Keep what we have
    - Pros: No API breaking change
    - Cons: Non-Pythonic A.F., so un-Pythonic that it's not possible to document properly using standard tools in  a way that is not completely unnatural
- Use factory `from_xzy` methods:
   - Pros: Pythonic, easy to maintain and document
   - Cons: API breaking change
 - Use a kwargs-based constructor alongside the factory methods
   - Pros: kinda Pythonic, only mild breaking change (e.g. for users that call via `data=` but still breaking for those calling raw constructors without named argument)
   - Cons: a mess to maintain (i.e., convoluted if/else logic between kwargs) and document

Thoughts ?

**Comment by tvatter** [comment]
Regarding approach 3, I juste tried something to ensure it was even feasible:

https://github.com/vinecopulib/pyvinecopulib/pull/163

It definitely works, at the cost of using the dreaded "new".

However, in additionally to being convoluted in the if/else logic, and a huge mess to document, there's another "issue". Doing e.g. `pv.Bicop(family="gaussian")` or `pv.Bicop(data=[[0.01, 0.05]])` both error with 

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: std::bad_cast
```

Instead of e.g. 

```
>>> pv.Bicop.from_family(family="gaussian")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: from_family(): incompatible function arguments. The following argument types are supported:
    1. from_family(family: pyvinecopulib.BicopFamily = BicopFamily.indep, rotation: int = 0, parameters: numpy.ndarray[dtype=float64, shape=(*, *)] = array([], shape=(0, 0), dtype=float64), var_types: collections.abc.Sequence[str] = ['c', 'c']) -> pyvinecopulib.Bicop

Invoked with types: kwargs = { family: str }
```

Or

```
>>> pv.Bicop.from_data(data=[[0.01, 0.05]])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: from_data(): incompatible function arguments. The following argument types are supported:
    1. from_data(data: numpy.ndarray[dtype=float64, shape=(*, 2), order='F'], controls: pyvinecopulib.FitControlsBicop = FitControlsBicop(), var_types: collections.abc.Sequence[str] = ['c', 'c']) -> pyvinecopulib.Bicop

Invoked with types: kwargs = { data: list }
```

The messy documentation of convoluted if/else logic is less of an issue IMO, but this is kind of a dealbreaker for me, as it gets us much closer to R's API where one has to check everything manually. @tnagler thoughts?

One last idea: we could also have undocumented overloaded constructors warning about deprecation in a future release.

**Comment by tvatter** [comment]
Code looks like this, but as I wrote it messes up the docstrings, which in turns means messing up the documentation

```
// Non-default constructors with deprecation warnings
    // .def(
    //   "__init__",
    //   [](Bicop* cop,
    //      const Eigen::Matrix<double, Eigen::Dynamic, 2>& data,
    //      const FitControlsBicop& controls,
    //      const std::vector<std::string>& var_types) {
    //     // Emit a warning for the deprecated constructor
    //     nb::module_::import_("warnings")
    //       .attr("warn")(
    //         "This constructor is deprecated. Use Bicop.from_data instead.",
    //         nb::module_::import_("DeprecationWarning"));
    //     // Construct the object in-place
    //     new (cop) Bicop(data, controls, var_types);
    //   },
    //   "data"_a,
    //   "controls"_a.sig("FitControlsBicop()") = FitControlsBicop(),
    //   "var_types"_a = std::vector<std::string>(2, "c"),
    //   bicop_doc.ctor.doc_3args_data_controls_var_types)

    // .def(
    //   "__init__",
    //   [](Bicop* cop, const std::string& filename) {
    //     // Emit a warning for the deprecated constructor
    //     nb::module_::import_("warnings")
    //       .attr("warn")(
    //         "This constructor is deprecated. Use Bicop.from_file instead.",
    //         nb::module_::import_("DeprecationWarning"));
    //     // Construct the object in-place
    //     new (cop) Bicop(filename);
    //   },
    //   "filename"_a,
    //   bicop_doc.ctor.doc_1args_filename)
```
